// Generated by CoffeeScript 1.12.4
var UIManager, findNodeHandle, measureInWindow;

findNodeHandle = require("react/lib/findNodeHandle");

UIManager = require("UIManager");

measureInWindow = function(view) {
  var node;
  node = findNodeHandle(view);
  return new Promise(function(resolve) {
    return UIManager.measureInWindow(node, function(left, top, width, height) {
      return resolve({
        left: left,
        top: top,
        width: width,
        height: height
      });
    });
  });
};

module.exports = measureInWindow;
